# Generated by Django 4.2.7 on 2025-03-06 18:46

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[blog.validators.validate_email_domain],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=255, validators=[blog.validators.validate_forbidden_words]
            ),
        ),
    ]
